name: 'servers'
version: 0.0.1
description: A set of simple servers for testing
author: Jim Philbin <jfphilbin@gmail.com>
homepage: https://github.com/Open-DICOMweb

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  odw:
    path:C:/github/odw/lib/odw.dart
  args: '>=0.13.0 <2.0.0'
  http: any
  http_parser: any
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
- dart_to_js_script_rewriter
