name: 'uploader'
version: 0.0.1
description: A set of simple servers for testing
author: Jim Philbin <jfphilbin@gmail.com>
homepage: https://github.com/Open-DICOMweb

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.13.0 <2.0.0'
  browser: any
  http: any
  http_parser: any
  odwhtml:
    path: C:/github/sdk2/odwhtml
#  dart_to_js_script_rewriter: '^0.1.0'

#transformers:
#- dart_to_js_script_rewriter
